server:
  port: 8000

spring:
  #  security:
  #    oauth2:
  #      client:
  #        registration:
  #          custom:
  #            client-id: sso-otus
  #            client-secret: sso-otus-secret
  #            scope: read,write
  #            authorization-grant-type: authorization_code
  #            redirect-uri: http://localhost:8000/health/
  #        provider:
  #          custom:
  #            authorization-uri: http://localhost:8000/health/
  #            token-uri: http://localhost:8000/health/
  #            user-info-uri: http://localhost:8000/health/
  #            user-name-attribute: preferred_username
  #  thymeleaf:
  #    cache: false
  #  cache:
  #    type: NONE
  jpa:
    show-sql: true
    database: postgresql
    properties:
      org:
        hibernate:
          envers:
            audit_table_suffix: _LOG
      hibernate:
        jdbc.batch_size: 20
        cache:
          use_query_cache: false
          use_second_level_cache: false
          use_structured_entries: false
          use_minimal_puts: false
        format_sql: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${DATASOURCE_URL}
    #    url: jdbc:postgresql://@evgpostgresdb-postgresql:5432/evg?user=evguser&password=evgpwd
    username: ${DATABASE_USER}
    #    username: evguser
    #    url: jdbc:postgresql://127.0.0.1:5432/evg?user=evguser&password=evgpwd
    password: ${DATABASE_PASSWORD}
    #    password: evgpwd
    driverClassName: org.postgresql.Driver
    #    continue-on-error: : true
    hikari:
      pool-name: HikariPool
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 150000
      max-lifetime: 300000
      connection-timeout: 5000
      register-mbeans: true
  transaction:
    default-timeout: 200

user:
  server: localhost:8000

